-- Table: BUS
CREATE TABLE BUS (
    id int  NOT NULL AUTO_INCREMENT,
    license_plate varchar(255)  NOT NULL,
    CONSTRAINT BUS_pk PRIMARY KEY (id)
);

-- Table: BUS_LINE
CREATE TABLE BUS_LINE (
    id int  NOT NULL AUTO_INCREMENT,
    name varchar(255)  NOT NULL,
    CONSTRAINT BUS_LINE_pk PRIMARY KEY (id)
);

-- Table: BUS_STOP
CREATE TABLE BUS_STOP (
    id int  NOT NULL AUTO_INCREMENT,
    name varchar(255)  NOT NULL,
    latitude varchar(255)  NOT NULL,
    longitude varchar(255)  NOT NULL,
    CONSTRAINT BUS_STOP_pk PRIMARY KEY (id)
);

-- Table: SERVING
CREATE TABLE SERVING (
    id int  NOT NULL AUTO_INCREMENT,
    BUS_id int  NOT NULL,
    BUS_LINE_id int  NOT NULL,
    CONSTRAINT SERVING_pk PRIMARY KEY (id)
);

-- Table: STOP_IN_LINE
CREATE TABLE STOP_IN_LINE (
    id int  NOT NULL AUTO_INCREMENT,
    BUS_STOP_id int  NOT NULL,
    BUS_LINE_id int  NOT NULL,
    CONSTRAINT STOP_IN_LINE_pk PRIMARY KEY (id)
);

-- foreign keys
-- Reference: SERVING_BUS (table: SERVING)
ALTER TABLE SERVING ADD CONSTRAINT SERVING_BUS
    FOREIGN KEY (BUS_id)
    REFERENCES BUS (id);

-- Reference: SERVING_BUS_LINE (table: SERVING)
ALTER TABLE SERVING ADD CONSTRAINT SERVING_BUS_LINE
    FOREIGN KEY (BUS_LINE_id)
    REFERENCES BUS_LINE (id);

-- Reference: STOP_IN_LINE_BUS_LINE (table: STOP_IN_LINE)
ALTER TABLE STOP_IN_LINE ADD CONSTRAINT STOP_IN_LINE_BUS_LINE
    FOREIGN KEY (BUS_LINE_id)
    REFERENCES BUS_LINE (id);

-- Reference: STOP_IN_LINE_BUS_STOP (table: STOP_IN_LINE)
ALTER TABLE STOP_IN_LINE ADD CONSTRAINT STOP_IN_LINE_BUS_STOP
    FOREIGN KEY (BUS_STOP_id)
    REFERENCES BUS_STOP (id);